const { defineConfig } = require("eslint-define-config");
const restrictedGlobals = require("eslint-restricted-globals");
require("@rushstack/eslint-patch/modern-module-resolution");

const baseConfig = defineConfig({
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:@cspell/recommended",
    "plugin:@typescript-eslint/recommended", // "plugin:import/recommended",
    // "plugin:import/typescript",
    "plugin:json/recommended-legacy",
    "plugin:promise/recommended",
  ],
  globals: {
    Atomics: "readonly",
    GeolocationPosition: true,
    GeolocationPositionError: true,
    JSX: true,
    logger: true,
    NodeJS: true,
    React: true,
    SharedArrayBuffer: "readonly",
  },
  ignorePatterns: [
    "!.mocharc.js",
    "!.vscode",
    "./*-lock.*",
    ".git",
    ".github",
    ".husky",
    ".idea",
    ".next",
    ".trunk",
    "*.d.ts",
    "*.env",
    "*.md",
    "*.sh",
    "*.svg",
    "*.txt",
    "build",
    "dist",
    "firebase-messaging-sw.js",
    "lib",
    "node_modules",
    "public",
    "temp",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: "latest",
    requireConfigFile: false,
    sourceType: "module",
  },
  plugins: [
    "@cspell",
    "@typescript-eslint",
    "import",
    "promise",
    "react",
    "unicorn",
    "unused-imports",
  ],
  rules: {
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-namespace": 0,
    "@typescript-eslint/no-unnecessary-type-constraint": [0],
    "@typescript-eslint/no-unused-vars": 0,
    "@typescript-eslint/no-var-requires": [0],
    "arrow-parens": "warn",
    camelcase: [0],
    "comma-dangle": 0,
    "generator-star-spacing": 0,
    "import/no-unresolved": [
      0,
      {
        amd: true,
        commonjs: true,
        esmodule: true,
        ignore: ["type-fest"],
      },
    ],
    "import/no-unused-modules": [
      "off",
      {
        missingExports: true,
        unusedExports: false,
      },
    ],
    "linebreak-style": ["warn", "unix"],
    "multiline-ternary": 0,
    "no-mixed-operators": 0,
    "no-mixed-spaces-and-tabs": 0,
    "no-restricted-globals": ["error"].concat(restrictedGlobals),
    "no-undef": "error",
    "no-unused-vars": "off",
    "no-var": "error",
    "object-shorthand": ["warn", "always"],
    quotes: ["off", "double"],
    semi: ["off", "always"],
    "@typescript-eslint/no-empty-object-type": "off",
    "sort-keys": [
      "off",
      "asc",
      {
        caseSensitive: false,
        minKeys: 2,
        natural: false,
      },
    ],
    "space-before-function-paren": 0,
    "unused-imports/no-unused-imports": "warn",
    "unused-imports/no-unused-vars": [
      "warn",
      {
        args: "after-used",
        argsIgnorePattern: "^_",
        ignoreRestSiblings: true,
        vars: "all",
        varsIgnorePattern: "^_",
      },
    ],
  },
});

module.exports = baseConfig;
