import {
  Asset,
  FeaturedPartners,
  FooterItem,
  HowItsWork,
  Icon,
  MarketTrend,
  NavItem,
  Security,
  SocialMedia,
  SmartLending,
  Section,
} from "~/types";
import {
  BorrowImage,
  Check,
  DefiSaver,
  Discord,
  Focus,
  InstaDapp,
  Lido,
  Shield,
  StakeHouse,
  Twitter,
  IdleFinance,
} from "~/assets/svgs";

export const smartLendingData: Section<SmartLending> = {
  id: "smart-lending",
  header: "Multi-Chain lending",
  heading: {
    left: "One Platform.",
    right: "Multi-Chain.",
  },
  description: "Multi-Chain Lending for Web3 in one platform.",
  items: [
    {
      to: "/",
      heading: "LIQUIDITY HUB",
      description:
        "Kylix is a multi-chain liquidity hub. With our innovative hub-and-spoke architecture, the protocol provides efficient and user-friendly access to liquidity across multiple blockchains.",
    },
    {
      to: "/",
      heading: "ONE-PLATFORM",
      description:
        "The Kylix Hub chain stores the entire state of the protocol and provides native lending for cross-chain liquidity managed directly to our lending hub. The unified state storage ensures consistency and avoids issues related to asynchronicity and race conditions between remote chains.",
    },
  ],
};

export const supportedAssetsData: Section<Asset> = {
  header: "Supported Chains",
  heading: { left: "Supported ", right: " CHAINS" },
  description: "Lend, Borrow and Earn seamlessly across:",
  id: "supported-assets-and-apy",
  items: [
    {
      src: "/assets/images/assets/avalaunch.png",
      alt: "Polkadot",
    },
    {
      src: "/assets/images/assets/btc.png",
      alt: "Solana",
    },
    {
      src: "/assets/images/assets/eth.png",
      alt: "Ethereum",
    },
    {
      src: "/assets/images/assets/usdc.png",
      alt: "MintLayer",
    },
  ],
};
export const howItsWorksData: Section<HowItsWork> = {
  header: "Why Kylix?",
  heading: {
    left: "Why",
    right: "Kylix Finance?",
  },
  description:
    " A new-generation DeFi Lending Platform with self-repaying loans and an on-chain marketplace for collateral liquidation.",
  id: "how-it's-works",
  items: [
    {
      id: "deposit",
      heading: "Deposit",
      description:
        "Lorem ipsum dolor sit amet consectetur. Duis viverra at eu sapien venenatis sed ut. Quis ullamcorper enim posuere dui est euismod blandit nunc. ",
    },
    {
      id: "convert",
      heading: "Convert",
      description:
        "Convert your deposit into a interest bearing token directly on our LST partner Acala through an integrated seamless process",
    },
    {
      id: "borrow",
      heading: "Borrow",
      description:
        "Borrow token and enjoy your loan with negative interest rates , getting repaid through time.",
      image: BorrowImage,
    },
  ],
};
export const securityAndAuditsData: Section<Security> = {
  header: "Security",
  heading: {
    left: "Security",
    right: "and Audits",
  },
  description: "The new cross-chain Lending Platform, secured by Polkadot. 1",
  id: "security-and-audits",
  items: [
    {
      heading: "Security Measures",
      description:
        "Explanation of platform security protocols (e.g., smart contract audits, multi-signature wallets).",
      icon: Shield,
    },
    {
      heading: "Risk Mitigation",
      description:
        "How the platform protects users’ assets, with details on insurance funds, collateral liquidation processes, and audit reports.",
      icon: Focus,
    },
    {
      heading: "Audit Partners",
      description:
        "Names of third-party auditors or security firms that have reviewed the platform’s smart contracts.",
      icon: Check,
    },
  ],
};

export const marketTrendsData: Section<MarketTrend> = {
  header: "Unique Features",
  heading: {
    left: "Unique",
    right: "Features",
  },
  description:
    "Unique and advanced lending products and services for the DeFi ecosystem.",
  id: "markets-trends",
  items: [
    {
      id: 0,
      label: "A New Lending Protocol",
      image: "/assets/images/market-trends/0.png",
      items: [
        {
          title: "Lending and Borrowing",
          description:
            "An on-chain & multi-chain asset lending platform built on Substrate.",
        },
        {
          title: "Automated Treasury",
          description:
            "An automated Treasury that distributes rewards to incentivise lenders to provide liquidity.",
        },
        {
          title: "Self-Repaying Loans",
          description:
            "Debt positions can be automatically repaid from the income generated by selected collaterals.",
        },
      ],
      actions: {
        primary: {
          label: "Learn More",
          action: () => {
            console.log("Lending: Learn More clicked");
          },
        },
        secondary: {
          label: "Get Started",
          action: () => {
            console.log("Lending: Get Started clicked");
          },
        },
      },
    },
    {
      id: 1,
      label: "Treasury Process",
      image: "/assets/images/market-trends/0.png",
      items: [
        {
          title: "New Interest Rates",
          description:
            "A new-generation of lending pool powered by polynomial interest rates, to enforce optimal usage of idle liquidity",
        },
        {
          title: "Collateral Scoring",
          description:
            "Debt Position determined by the quality of the collateral, introducing collateral scoring.",
        },
        {
          title: "Rewards Distribution",
          description:
            "Liquidity from the Treasury distributed to Borrowers and Liquid staking partners as rewards.",
        },
      ],
      actions: {
        primary: {
          label: "Explore DEX",
          action: () => {
            console.log("DEX: Explore clicked");
          },
        },
        secondary: {
          label: "Start Trading",
          action: () => {
            console.log("DEX: Start Trading clicked");
          },
        },
      },
    },
    {
      id: 2,
      label: "Collateral Marketplace",
      image: "/assets/images/market-trends/0.png",
      items: [
        {
          title: "Collateral Marketplace",
          description:
            "An marketplace that allows users to bid on liquidated collateral.",
        },
        {
          title: "Arbitrage Opportunities",
          description:
            "It offers an arbitrage opportunity for users, to bid and acquire assets at a discount to the market price.",
        },
        {
          title: "Self Repaying Loans",
          description:
            "Debt positions can be automatically repaid from the income generated by selected collateral",
        },
      ],
      actions: {
        primary: {
          label: "Explore NFTs",
          action: () => {
            console.log("NFT: Explore clicked");
          },
        },
        secondary: {
          label: "Mint Now",
          action: () => {
            console.log("NFT: Mint Now clicked");
          },
        },
      },
    },
  ],
};
export const featuredPartnersData: Section<FeaturedPartners> = {
  header: "Featured partners",
  id: "featured-partners",
  heading: {
    left: "Proudly Supported By",
  },
  items: [
    {
      link: "/",
      name: "Decentralised Future",
      icon: InstaDapp,
    },
    {
      link: "/",
      name: "Equito Network",
      icon: IdleFinance,
    },
    {
      link: "/",
      name: "Hercle Financial",
      icon: Lido,
    },
    {
      link: "/",
      name: "Harbour Industrial Capital",
      icon: DefiSaver,
    },
    {
      link: "/",
      name: "Pendulum",
      icon: StakeHouse,
    },
    {
      link: "/",
      name: "Polimec",
      icon: StakeHouse,
    },
    {
      link: "/",
      name: "BlockDeep",
      icon: StakeHouse,
    },
  ],
};
export const navItems: NavItem[] = [
  smartLendingData.header && {
    label: smartLendingData.header,
    link: `#${smartLendingData.id}`,
  },
  marketTrendsData.header && {
    label: marketTrendsData.header,
    link: `#${marketTrendsData.id}`,
  },
  supportedAssetsData.header && {
    label: supportedAssetsData.header,
    link: `#${supportedAssetsData.id}`,
  },
  howItsWorksData.header && {
    label: howItsWorksData.header,
    link: `#${howItsWorksData.id}`,
  },
  securityAndAuditsData.header && {
    label: securityAndAuditsData.header,
    link: `#${securityAndAuditsData.id}`,
  },
  featuredPartnersData.header && {
    label: featuredPartnersData.header,
    link: `#${featuredPartnersData.id}`,
  },
].filter((item): item is NavItem => !!item);

interface Footer {
  left: SocialMedia[];
  right: FooterItem[];
}

export const footerData: Footer = {
  left: [
    {
      name: "X",
      link: "https://x.com/kylixfinance",
      icon: Twitter,
    },
    {
      name: "Discord",
      link: "https://discord.gg/UkRcWaTh5p",
      icon: Discord,
    },
  ],
  right: [
    {
      title: "Products",
      items: [
        {
          label: "Lending",
          link: "lending",
        },
        {
          label: "Borrowing",
          link: "borrowing",
        },
        {
          label: "Markets",
          link: "markets",
        },
      ],
    },
    {
      title: "Tools",
      items: [
        {
          label: "Tokens",
          link: "tokens",
        },
        {
          label: "Convert",
          link: "convert",
        },
        {
          label: "Explore Traders",
          link: "exploreTraders",
        },
        {
          label: "Pricing",
          link: "pricing",
        },
      ],
    },
    {
      title: "Support",
      items: [
        {
          label: "Beginners Guide",
          link: "beginnersGuide",
        },
        {
          label: "Help Center",
          link: "helpCenter",
        },
        {
          label: "Feedbacks",
          link: "feedbacks",
        },
        {
          label: "API Doc",
          link: "apiDoc",
        },
      ],
    },
  ],
};
